site_name: Nikhil Venkatachalam's Website
# Navigation bar
nav:
  - Home: index.md
  - Resume: resume.md
  - Timeline: timeline.md

markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.details
    - pymdownx.superfences

extra_css:
  - stylesheets/extra.css?v=2

extra_javascript:
  - javascripts/resume.js?v=1

theme:
  name: material

  icon:
    logo: fontawesome/solid/n
  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red 
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  
  favicon: images/favicon.png
