site_name: Nikhil Venkatachalam's Website
# Navigation bar
nav:
  - Resume: index.md
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: red
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  favicon: images/favicon.png

